# language: python
imports:
    - python
tools:
    python_analyzer:
        config:
            metrics: true
            duplication_detector:
                enabled: true
    pylint:
        python_version: 2
checks:
    python:
        code_rating: true
